version: '3'

services:
  nginx:
    image: nginx:1.13
    container_name: django.nginx
    ports:
      - "8000:8000"
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/log:/var/log/nginx
      - ./static:/code/static
      - ./media:/code/media
      - ./yiwu.sock:/code/yiwu.sock
    depends_on:
      - web
  db:
    image: mysql:5.7.12
    expose: 
      - "3306"
    # command:mysql -uroot -p123456 yiwu < yiwu.sql
    volumes:
      - ./db/msql:/var/lib/mysql
      - ./yiwu.sql:/sql/yiwu.sql
    environment:
      - MYSQL_DATABASE=yiwu
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    image: redis:3.0.6
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/data:/data
      - ./db/redis:/var/lib/redis
    # command: redis-server /var/lib/redis/redis.conf
    environment: 
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  
  web:
    build: .
    command: uwsgi --ini /code/conf/wu_uwsgi.ini
    ports:
      - "8887:8887"
    volumes:
      - .:/code
      - ./ulog:/code/ulog
    depends_on:
      - db
      - redis

